# CircleCI 的版本
version: 2.1

jobs:
  # 把這個工作取名叫做 `build-and-test`
  build-and-test:
    # 告訴 circleci，我需要 docker 的環境
    docker:
      # 告訴 circleci，我要用 Docker Hub 上的
      # `circleci/python` 的映像檔	
      # 而且 tag 是要 3.8.1 的 tag
      - image: circleci/python:3.8.1
    steps:
      # 第一步
      - checkout
      # 第二步
      - run:
          # 先安裝 django
          command: |
            pip install django~=3.0.3
          # 只是幫這個指令取名字而已
          name: Install
      # 第三步
      - run:
          # 執行 django 的測試
          command: |
            python blog_project/blog/manage.py test
          name: Test

# 告訴 CircleCI，我要執行的工作，
# 總共要執行 `build-and-test` 這一個工作
workflows:
  main:
    jobs:
      - build-and-test